<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="base_link"/>

  <!-- drive wheels side profile (front) -->
  <joint name="base_profile_joint_A" type="fixed">
    <parent link="base_link"/>
    <child  link="base_profile_A"/>
    <origin xyz="${long_profile_length/2-profile_width/2} 0 0" rpy="0 0 0"/>
  </joint>
  <link name="base_profile_A">
    <visual>
      <xacro:short_profile_geometry/>
      <material name="aluminium"/>
    </visual>
    <collision>
      <xacro:short_profile_geometry/>
    </collision>
    <inertial>
      <xacro:short_profile_geometry/>
      <mass value="${short_profile_mass}"/>
      <xacro:box_inertia m="${short_profile_mass}" x="${profile_width}" y="${short_profile_length}" z="${profile_height}" />
    </inertial>
  </link>
  <gazebo reference="base_profile_A">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- side profile -->
  <joint name="base_profile_joint_B" type="fixed">
    <parent link="base_link"/>
    <child  link="base_profile_B"/>
    <origin xyz="0 ${short_profile_length/2+profile_width/2} 0" rpy="0 0 ${pi/2}"/>
  </joint>
  <link name="base_profile_B">
    <visual>
      <xacro:long_profile_geometry/>
      <material name="aluminium"/>
    </visual>
    <collision>
      <xacro:long_profile_geometry/>
    </collision>
    <inertial>
      <xacro:long_profile_geometry/>
      <mass value="${long_profile_mass}"/>
      <xacro:box_inertia m="${long_profile_mass}" x="${profile_width}" y="${long_profile_length}" z="${profile_height}" />
    </inertial>
  </link>
  <gazebo reference="base_profile_B">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- caster wheels side profile (rear) -->
  <joint name="base_profile_joint_C" type="fixed">
    <parent link="base_link"/>
    <child  link="base_profile_C"/>
    <origin xyz="${-long_profile_length/2+profile_width/2} 0 0" rpy="0 0 0"/>
  </joint>
  <link name="base_profile_C">
    <visual>
      <xacro:short_profile_geometry/>
      <material name="aluminium"/>
    </visual>
    <collision>
      <xacro:short_profile_geometry/>
    </collision>
    <inertial>
      <xacro:short_profile_geometry/>
      <mass value="${short_profile_mass}"/>
      <xacro:box_inertia m="${short_profile_mass}" x="${profile_width}" y="${short_profile_length}" z="${profile_height}" />
    </inertial>
  </link>
  <gazebo reference="base_profile_C">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- side profile -->
  <joint name="base_profile_joint_D" type="fixed">
    <parent link="base_link"/>
    <child  link="base_profile_D"/>
    <origin xyz="0 ${-short_profile_length/2-profile_width/2} 0" rpy="0 0 ${pi/2}"/>
  </joint>
  <link name="base_profile_D">
    <visual>
      <xacro:long_profile_geometry/>
      <material name="aluminium"/>
    </visual>
    <collision>
      <xacro:long_profile_geometry/>
    </collision>
    <inertial>
      <xacro:long_profile_geometry/>
      <mass value="${long_profile_mass}"/>
      <xacro:box_inertia m="${long_profile_mass}" x="${profile_width}" y="${long_profile_length}" z="${profile_height}" />
    </inertial>
  </link>
  <gazebo reference="base_profile_D">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- battery and slot/holder -->

  <joint name="battery_holder_joint" type="fixed">
    <parent link="base_profile_A"/>
    <child  link="battery_holder_link"/>
    <origin xyz="${-battery_holder_length+profile_width/2} 0 ${-profile_height/2}" rpy="0 0 0"/>
  </joint>
  <link name="battery_holder_link">
    <visual>
      <origin xyz="0 ${battery_holder_width/2} 0" rpy="${pi} 0 0"/>
      <geometry>
        <mesh filename="package://tortuga/meshes/battery_holder.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="plastic"/>
    </visual>
    <collision>
      <origin xyz="${battery_holder_length/2} 0 ${-battery_holder_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${battery_holder_length} ${battery_holder_width} ${battery_holder_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${battery_holder_length/2} 0 ${-battery_holder_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${battery_holder_length} ${battery_holder_width} ${battery_holder_height}"/>
      </geometry>
      <mass value="${battery_holder_mass}"/>
      <xacro:box_inertia m="${battery_holder_mass}" x="${battery_holder_length}" y="${battery_holder_width}" z="${battery_holder_height}" />
    </inertial>
  </link>
  <gazebo reference="battery_holder_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="battery_joint" type="fixed">
    <parent link="battery_holder_link"/>
    <child  link="battery_link"/>
    <origin xyz="${battery_length/2} 0 ${-battery_holder_height/2-battery_height}" rpy="${pi} 0 0"/>
  </joint>
  <link name="battery_link">
    <visual>
      <origin xyz="-${battery_length/2} ${battery_holder_width/2} 0" rpy="${pi} 0 0"/>
      <geometry>
        <mesh filename="package://tortuga/meshes/battery.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="plastic"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-battery_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${battery_length} ${battery_width} ${battery_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${-battery_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${battery_length} ${battery_width} ${battery_height}"/>
      </geometry>
      <mass value="${battery_mass}"/>
      <xacro:box_inertia m="${battery_mass}" x="${battery_length}" y="${battery_width}" z="${battery_height}" />
    </inertial>
  </link>
  <gazebo reference="battery_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="cover_deck_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="cover_deck"/>
    <origin xyz="0 0 ${profile_height/2+0.0065}" rpy="0 0 0"/>
  </joint>
  <link name="cover_deck">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${long_profile_length} 0.28 0.013"/>
      </geometry>
      <material name="plastic"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${long_profile_length} 0.28 0.013"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="cover_deck">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="bottom_deck_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="bottom_deck"/>
    <origin xyz="0 0 -0.004" rpy="0 0 0"/>
  </joint>
  <link name="bottom_deck">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${long_profile_length-profile_width*2} ${0.28-profile_width*2} 0.013"/>
      </geometry>
      <material name="plastic"/>
    </visual>
  </link>
  <gazebo reference="cover_deck">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="front_lamps_joint" type="fixed">
    <parent link="cover_deck"/>
    <child  link="front_lamps_link"/>
    <origin xyz="${long_profile_length/2} 0 0" rpy="${pi/2} 0 ${pi/2}"/>
  </joint>
  <link name="front_lamps_link">
    <visual>
      <origin xyz="-0.188 -0.0265 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://tortuga/meshes/front_lamps.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black_plastic"/>
    </visual>
    <collision>
      <origin xyz="0 -0.01 0.01" rpy="0 0 0"/>
      <geometry>
        <box size="${short_profile_length+2*profile_width} ${profile_width} ${profile_width/2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 -0.01 0.01" rpy="0 0 0"/>
      <geometry>
        <box size="${short_profile_length+2*profile_width} ${profile_width} ${profile_width/2}"/>
      </geometry>
      <mass value="0.1"/>
      <xacro:box_inertia m="0.1" x="${short_profile_length+2*profile_width}" y="${profile_width}" z="${profile_width/2}" />
    </inertial>
  </link>
  <gazebo reference="front_lamps_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="rear_lamps_joint" type="fixed">
    <parent link="cover_deck"/>
    <child  link="rear_lamps_link"/>
    <origin xyz="${-long_profile_length/2} 0 0" rpy="${-pi/2} 0 ${pi/2}"/>
  </joint>
  <link name="rear_lamps_link">
    <visual>
      <origin xyz="-0.14 -0.0065 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://tortuga/meshes/rear_lamps.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black_plastic"/>
    </visual>
    <collision>
      <origin xyz="0 0.01 0.01" rpy="0 0 0"/>
      <geometry>
        <box size="${short_profile_length+2*profile_width} ${profile_width} ${profile_width/2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0.01 0.01" rpy="0 0 0"/>
      <geometry>
        <box size="${short_profile_length+2*profile_width} ${profile_width} ${profile_width/2}"/>
      </geometry>
      <mass value="0.1"/>
      <xacro:box_inertia m="0.1" x="${short_profile_length+2*profile_width}" y="${profile_width}" z="${profile_width/2}" />
    </inertial>
  </link>
  <gazebo reference="rear_lamps_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

</robot>
